/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package municipalidad.presentacion.vistas;

import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Coyote
 */
public class PanelAsignarBeneficio extends javax.swing.JPanel {

    /**
     * Creates new form PanelAsignarBeneficio
     */
    public PanelAsignarBeneficio() {
        initComponents();
        this.setBounds(0, 0, 800, 600);
        this.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        lblTipoBeneficio = new javax.swing.JLabel();
        cbxTipoBeneficio = new javax.swing.JComboBox<>();
        lblEstablecimiento = new javax.swing.JLabel();
        cbxEstablecimiento = new javax.swing.JComboBox<>();
        lblCarrera = new javax.swing.JLabel();
        cbxCarrera = new javax.swing.JComboBox<>();
        lblDocumentos = new javax.swing.JLabel();
        chxFotocopia = new javax.swing.JCheckBox();
        chxConstancia = new javax.swing.JCheckBox();
        lblObligatorio = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        lblDni = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        chxCertificadoResidencia = new javax.swing.JCheckBox();
        chxNegativaAnses = new javax.swing.JCheckBox();
        chxBoletaServicio = new javax.swing.JCheckBox();
        btnLimpiar = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setPreferredSize(new java.awt.Dimension(800, 600));

        lblTipoBeneficio.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTipoBeneficio.setText("Tipo de Beneficio:");

        lblEstablecimiento.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblEstablecimiento.setText("Establecimiento:");

        lblCarrera.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCarrera.setText("Carrera:");

        lblDocumentos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblDocumentos.setText("Documentos  :");

        chxFotocopia.setBackground(new java.awt.Color(204, 204, 255));
        chxFotocopia.setText("Fotocopia de DNI  *");

        chxConstancia.setBackground(new java.awt.Color(204, 204, 255));
        chxConstancia.setText("Constancia de estudios en curso *");

        lblObligatorio.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        lblObligatorio.setForeground(new java.awt.Color(255, 0, 0));
        lblObligatorio.setText("( * Obligatorio)");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        lblDni.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblDni.setText("DNI");

        lblNombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNombre.setText("Nombre:");

        txtNombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        txtDni.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        chxCertificadoResidencia.setBackground(new java.awt.Color(204, 204, 255));
        chxCertificadoResidencia.setText("Certificado de Residencia");

        chxNegativaAnses.setBackground(new java.awt.Color(204, 204, 255));
        chxNegativaAnses.setText("Negativa Anses/Boleta de Sueldo");

        chxBoletaServicio.setBackground(new java.awt.Color(204, 204, 255));
        chxBoletaServicio.setText("Boleta de Servicio");

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165)
                .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbxCarrera, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEstablecimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbxEstablecimiento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblObligatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(chxFotocopia, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(chxConstancia))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(chxBoletaServicio)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(chxCertificadoResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(chxNegativaAnses)))))
                                .addGap(0, 98, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTipoBeneficio, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNombre))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbxTipoBeneficio, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDni)
                                .addGap(127, 127, 127)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnBuscar)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDni)
                            .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre)
                            .addComponent(txtNombre))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTipoBeneficio)
                            .addComponent(cbxTipoBeneficio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstablecimiento)
                    .addComponent(cbxEstablecimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarrera)
                    .addComponent(cbxCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDocumentos)
                    .addComponent(lblObligatorio))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chxFotocopia)
                    .addComponent(chxCertificadoResidencia)
                    .addComponent(chxNegativaAnses))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chxConstancia)
                    .addComponent(chxBoletaServicio))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnConfirmar)
                    .addComponent(btnLimpiar))
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void limpiar() {
        txtDni.setText(null);
        txtNombre.setText(null);
        chxBoletaServicio.setSelected(false);
        chxCertificadoResidencia.setSelected(false);
        chxConstancia.setSelected(false);
        chxFotocopia.setSelected(false);
        chxNegativaAnses.setSelected(false);
        lblImagen.setIcon(null);
    }

    public boolean verificarCondiciones() {
        boolean b = false;
        if (chxFotocopia.isSelected() && chxConstancia.isSelected()) {
            b = true;
        } else {
            JOptionPane.showMessageDialog(null, "Faltan documentos obligatorios.");
        }
        if (txtNombre.getText().length() == 0) {
            b = false;
            JOptionPane.showMessageDialog(null, "Ingresar beneficiario.");
        }
        return b;
    }

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
       
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void txtDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbxCarrera;
    private javax.swing.JComboBox<String> cbxEstablecimiento;
    private javax.swing.JComboBox<String> cbxTipoBeneficio;
    private javax.swing.JCheckBox chxBoletaServicio;
    private javax.swing.JCheckBox chxCertificadoResidencia;
    private javax.swing.JCheckBox chxConstancia;
    private javax.swing.JCheckBox chxFotocopia;
    private javax.swing.JCheckBox chxNegativaAnses;
    private javax.swing.JLabel lblCarrera;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblDocumentos;
    private javax.swing.JLabel lblEstablecimiento;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblObligatorio;
    private javax.swing.JLabel lblTipoBeneficio;
    private javax.swing.JTextField txtDni;
    private javax.swing.JLabel txtNombre;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the btnBuscar
     */
    public JLabel getLabelImagen() {
        return lblImagen;
    }

    public javax.swing.JButton getBtnBuscar() {
        return btnBuscar;
    }

    /**
     * @return the btnCancelar
     */
    public javax.swing.JButton getBtnCancelar() {
        return btnCancelar;
    }

    /**
     * @return the btnConfirmar
     */
    public javax.swing.JButton getBtnConfirmar() {
        return btnConfirmar;
    }

    /**
     * @return the btnLimpiar
     */
    public javax.swing.JButton getBtnLimpiar() {
        return btnLimpiar;
    }

    /**
     * @return the cbxCarrera
     */
    public javax.swing.JComboBox<String> getCbxCarrera() {
        return cbxCarrera;
    }

    /**
     * @return the cbxEstablecimiento
     */
    public javax.swing.JComboBox<String> getCbxEstablecimiento() {
        return cbxEstablecimiento;
    }

    /**
     * @return the cbxTipoBeneficio
     */
    public javax.swing.JComboBox<String> getCbxTipoBeneficio() {
        return cbxTipoBeneficio;
    }

    /**
     * @return the cbxNegativaAnses
     */
    public javax.swing.JCheckBox getChxNegativaAnses() {
        return chxNegativaAnses;
    }

    /**
     * @return the chxBoletaServicio
     */
    public javax.swing.JCheckBox getChxBoletaServicio() {
        return chxBoletaServicio;
    }

    /**
     * @return the chxCertificadoResidencia
     */
    public javax.swing.JCheckBox getChxCertificadoResidencia() {
        return chxCertificadoResidencia;
    }

    /**
     * @return the chxConstancia
     */
    public javax.swing.JCheckBox getChxConstancia() {
        return chxConstancia;
    }

    /**
     * @return the chxFotocopia
     */
    public javax.swing.JCheckBox getChxFotocopia() {
        return chxFotocopia;
    }

    /**
     * @return the txtDni
     */
    public javax.swing.JTextField getTxtDni() {
        return txtDni;
    }

    /**
     * @return the txtNombre
     */
    public javax.swing.JLabel getTxtNombre() {
        return txtNombre;
    }

}
