/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package municipalidad.presentacion.vistas;

/**
 *
 * @author Coyote
 */
public class PanelEntregaBoletos extends javax.swing.JPanel {

    /**
     * Creates new form PanelEntregaBoletos
     */
    public PanelEntregaBoletos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblDni = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblTipoBeneficio = new javax.swing.JLabel();
        lblCarnetEjempar = new javax.swing.JLabel();
        lblEntrega = new javax.swing.JLabel();
        lblPeriodo = new javax.swing.JLabel();
        lblRealizada = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();
        lblEntregadoA = new javax.swing.JLabel();
        chxBeneficiario = new javax.swing.JRadioButton();
        chxFamiliar = new javax.swing.JRadioButton();
        lblDniFamiliar = new javax.swing.JLabel();
        lblParentezco = new javax.swing.JLabel();
        txtDniFamiliar = new javax.swing.JTextField();
        txtParentezco = new javax.swing.JTextField();
        txtDni = new javax.swing.JTextField();
        txtNombre = new javax.swing.JLabel();
        txtTipoBeneficio = new javax.swing.JLabel();
        txtEntregaNro = new javax.swing.JLabel();
        txtCarnetEjemplar = new javax.swing.JLabel();
        txtPeriodo = new javax.swing.JLabel();
        txtRealizada = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        lblDni.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblDni.setText("DNI:");

        lblNombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNombre.setText("Nombre:");

        lblTipoBeneficio.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTipoBeneficio.setText("Tipo de Beneficio:");

        lblCarnetEjempar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCarnetEjempar.setText("Carnet Ejemplar:");

        lblEntrega.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblEntrega.setText("Entrega Nro:");

        lblPeriodo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblPeriodo.setText("Periodo:");

        lblRealizada.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblRealizada.setText("Realizada:");

        lblImagen.setText(".                                                        ,");

        lblEntregadoA.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblEntregadoA.setText("Entregado a:");

        chxBeneficiario.setBackground(new java.awt.Color(204, 204, 255));
        chxBeneficiario.setText("Beneficiario");

        chxFamiliar.setBackground(new java.awt.Color(204, 204, 255));
        chxFamiliar.setText("Familiar");

        lblDniFamiliar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblDniFamiliar.setText("DNI:");

        lblParentezco.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblParentezco.setText("Parentezco:");

        txtDniFamiliar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtParentezco.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtDni.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtNombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtNombre.setText(".                                                              .");

        txtTipoBeneficio.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtTipoBeneficio.setText(".                                                              .");

        txtEntregaNro.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtEntregaNro.setText(". ");

        txtCarnetEjemplar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtCarnetEjemplar.setText(". ");

        txtPeriodo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtPeriodo.setText(".                                                .");

        txtRealizada.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtRealizada.setText(". ");

        btnBuscar.setText("Buscar");

        btnCancelar.setText("Cancelar");

        btnConfirmar.setText("Confirmar Entrega");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDniFamiliar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblParentezco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtParentezco, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDniFamiliar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTipoBeneficio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTipoBeneficio, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chxFamiliar)
                            .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEntregadoA, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chxBeneficiario))
                        .addGap(175, 175, 175))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDni, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                                        .addComponent(btnBuscar))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEntrega)
                                    .addComponent(lblCarnetEjempar)
                                    .addComponent(lblPeriodo))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCarnetEjemplar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtEntregaNro, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(lblRealizada, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtRealizada, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(362, 362, 362))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDni)
                            .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTipoBeneficio)
                            .addComponent(txtTipoBeneficio)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNombre)
                        .addComponent(txtNombre)))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEntregadoA)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCarnetEjempar)
                        .addComponent(txtCarnetEjemplar)))
                .addGap(29, 29, 29)
                .addComponent(chxBeneficiario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chxFamiliar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEntrega)
                        .addComponent(lblRealizada)
                        .addComponent(txtEntregaNro)
                        .addComponent(txtRealizada)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDniFamiliar)
                    .addComponent(txtDniFamiliar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPeriodo)
                            .addComponent(txtPeriodo)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblParentezco)
                            .addComponent(txtParentezco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnConfirmar))
                .addGap(42, 42, 42))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton chxBeneficiario;
    private javax.swing.JRadioButton chxFamiliar;
    private javax.swing.JLabel lblCarnetEjempar;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblDniFamiliar;
    private javax.swing.JLabel lblEntrega;
    private javax.swing.JLabel lblEntregadoA;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblParentezco;
    private javax.swing.JLabel lblPeriodo;
    private javax.swing.JLabel lblRealizada;
    private javax.swing.JLabel lblTipoBeneficio;
    private javax.swing.JLabel txtCarnetEjemplar;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtDniFamiliar;
    private javax.swing.JLabel txtEntregaNro;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JTextField txtParentezco;
    private javax.swing.JLabel txtPeriodo;
    private javax.swing.JLabel txtRealizada;
    private javax.swing.JLabel txtTipoBeneficio;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the btnBuscar
     */
    public javax.swing.JButton getBtnBuscar() {
        return btnBuscar;
    }

    /**
     * @return the buttonGroup1
     */
    public javax.swing.ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }

    /**
     * @return the chxBeneficiario
     */
    public javax.swing.JRadioButton getChxBeneficiario() {
        return chxBeneficiario;
    }

    /**
     * @return the chxFamiliar
     */
    public javax.swing.JRadioButton getChxFamiliar() {
        return chxFamiliar;
    }

    /**
     * @return the txtCarnetEjemplar
     */
    public javax.swing.JLabel getTxtCarnetEjemplar() {
        return txtCarnetEjemplar;
    }

    /**
     * @return the txtDni
     */
    public javax.swing.JTextField getTxtDni() {
        return txtDni;
    }

    /**
     * @return the txtDniFamiliar
     */
    public javax.swing.JTextField getTxtDniFamiliar() {
        return txtDniFamiliar;
    }

    /**
     * @return the txtEntregaNro
     */
    public javax.swing.JLabel getTxtEntregaNro() {
        return txtEntregaNro;
    }

      /**
     * @return the lblImagen
     */
    
    public javax.swing.JLabel getLblImagen(){
        return lblImagen;
    }
    
    /**
     * @return the txtNombre
     */
    public javax.swing.JLabel getTxtNombre() {
        return txtNombre;
    }

    /**
     * @return the txtParentezco
     */
    public javax.swing.JTextField getTxtParentezco() {
        return txtParentezco;
    }

    /**
     * @return the txtPeriodo
     */
    public javax.swing.JLabel getTxtPeriodo() {
        return txtPeriodo;
    }

    /**
     * @return the txtRealizada
     */
    public javax.swing.JLabel getTxtRealizada() {
        return txtRealizada;
    }

    /**
     * @return the txtTipoBeneficio
     */
    public javax.swing.JLabel getTxtTipoBeneficio() {
        return txtTipoBeneficio;
    }

    /**
     * @return the btnCancelar
     */
    public javax.swing.JButton getBtnCancelar() {
        return btnCancelar;
    }

    /**
     * @return the btnConfirmar
     */
    public javax.swing.JButton getBtnConfirmar() {
        return btnConfirmar;
    }
}
