/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package municipalidad.presentacion.vistas;

/**
 *
 * @author Coyote
 */
public class PanelRenovacion extends javax.swing.JPanel {

    /**
     * @return the btnBuscar
     */
    public javax.swing.JButton getBtnBuscar() {
        return btnBuscar;
    }

    /**
     * @return the btnCancelar
     */
    public javax.swing.JButton getBtnCancelar() {
        return btnCancelar;
    }

    /**
     * @return the btnConfirmar
     */
    public javax.swing.JButton getBtnConfirmar() {
        return btnConfirmar;
    }

    /**
     * @return the lblImagen
     */
    public javax.swing.JLabel getLblImagen() {
        return lblImagen;
    }

    /**
     * @return the txtCarnetEjemplar
     */
    public javax.swing.JLabel getTxtCarnetEjemplar() {
        return txtCarnetEjemplar;
    }

    /**
     * @return the txtCarrera
     */
    public javax.swing.JLabel getTxtCarrera() {
        return txtCarrera;
    }

    /**
     * @return the txtDni
     */
    public javax.swing.JTextField getTxtDni() {
        return txtDni;
    }

    /**
     * @return the txtEstablecimiento
     */
    public javax.swing.JLabel getTxtEstablecimiento() {
        return txtEstablecimiento;
    }

    /**
     * @return the txtNombre
     */
    public javax.swing.JLabel getTxtNombre() {
        return txtNombre;
    }

    /**
     * @return the txtPeriodo
     */
    public javax.swing.JLabel getTxtPeriodo() {
        return txtPeriodo;
    }

    /**
     * @return the txtRealizado
     */
    public javax.swing.JLabel getTxtRealizado() {
        return txtRealizado;
    }

    /**
     * @return the txtRenovacion
     */
    public javax.swing.JLabel getTxtRenovacion() {
        return txtRenovacion;
    }

    /**
     * @return the txtTipoBeneficio
     */
    public javax.swing.JLabel getTxtTipoBeneficio() {
        return txtTipoBeneficio;
    }

    /**
     * Creates new form PanelRenovacion
     */
    public PanelRenovacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDni = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblTipoBeneficio = new javax.swing.JLabel();
        lblCarnetEjemplar = new javax.swing.JLabel();
        lblRenovacionNro = new javax.swing.JLabel();
        lblRealizado = new javax.swing.JLabel();
        lblPeriodo = new javax.swing.JLabel();
        lblCarrera = new javax.swing.JLabel();
        lblEstablecimiento = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        txtNombre = new javax.swing.JLabel();
        txtTipoBeneficio = new javax.swing.JLabel();
        txtCarnetEjemplar = new javax.swing.JLabel();
        txtRenovacion = new javax.swing.JLabel();
        txtPeriodo = new javax.swing.JLabel();
        txtCarrera = new javax.swing.JLabel();
        txtRealizado = new javax.swing.JLabel();
        txtEstablecimiento = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        lblDni.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblDni.setText("DNI:");

        lblNombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNombre.setText("Nombre:");

        lblTipoBeneficio.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTipoBeneficio.setText("Tipo de Beneficio:");

        lblCarnetEjemplar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCarnetEjemplar.setText("Carnet Ejemplar:");

        lblRenovacionNro.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblRenovacionNro.setText("Renovacion Nro:");

        lblRealizado.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblRealizado.setText("Realizado:");

        lblPeriodo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblPeriodo.setText("Periodo:");

        lblCarrera.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCarrera.setText("Carrera:");

        lblEstablecimiento.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblEstablecimiento.setText("Establecimiento:");

        lblImagen.setText(".                                                        .");

        txtDni.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        btnBuscar.setText("Buscar");

        txtNombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtNombre.setText(".                                                     .");

        txtTipoBeneficio.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtTipoBeneficio.setText(".                                  .");

        txtCarnetEjemplar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtCarnetEjemplar.setText(".    ");

        txtRenovacion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtRenovacion.setText(".");

        txtPeriodo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtPeriodo.setText(".                                              .");

        txtCarrera.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtCarrera.setText(".                                                          .");

        txtRealizado.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtRealizado.setText(".");

        txtEstablecimiento.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtEstablecimiento.setText(".                                                          .");

        btnCancelar.setText("Cancelar");

        btnConfirmar.setText("Confirmar Renovacion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(173, 173, 173))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTipoBeneficio)
                                    .addComponent(lblCarnetEjemplar)
                                    .addComponent(lblRenovacionNro))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCarnetEjemplar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtTipoBeneficio, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtRenovacion, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblRealizado))))
                                .addGap(6, 6, 6)))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEstablecimiento)
                            .addComponent(lblCarrera)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtRealizado, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(lblPeriodo))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblDni)
                            .addGap(95, 95, 95)
                            .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnBuscar))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblNombre)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtEstablecimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                                .addComponent(txtCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(9, 9, 9)
                                    .addComponent(txtPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(41, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnConfirmar)
                        .addGap(41, 41, 41))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEstablecimiento)
                            .addComponent(txtEstablecimiento))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDni)
                            .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre)
                            .addComponent(txtNombre))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTipoBeneficio)
                            .addComponent(txtTipoBeneficio))
                        .addGap(78, 78, 78)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCarrera)
                        .addComponent(txtCarrera))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCarnetEjemplar)
                        .addComponent(txtCarnetEjemplar)))
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRenovacionNro)
                    .addComponent(txtRenovacion)
                    .addComponent(lblRealizado)
                    .addComponent(txtRealizado)
                    .addComponent(lblPeriodo)
                    .addComponent(txtPeriodo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnConfirmar))
                .addGap(52, 52, 52))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JLabel lblCarnetEjemplar;
    private javax.swing.JLabel lblCarrera;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblEstablecimiento;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPeriodo;
    private javax.swing.JLabel lblRealizado;
    private javax.swing.JLabel lblRenovacionNro;
    private javax.swing.JLabel lblTipoBeneficio;
    private javax.swing.JLabel txtCarnetEjemplar;
    private javax.swing.JLabel txtCarrera;
    private javax.swing.JTextField txtDni;
    private javax.swing.JLabel txtEstablecimiento;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JLabel txtPeriodo;
    private javax.swing.JLabel txtRealizado;
    private javax.swing.JLabel txtRenovacion;
    private javax.swing.JLabel txtTipoBeneficio;
    // End of variables declaration//GEN-END:variables
}
