/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package municipalidad.presentacion.vistas;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import municipalidad.dominio.Beneficiario;
import municipalidad.presentacion.interfaces.IVistaPrevia;
import municipalidad.presentacion.presentadores.VistaPreviaPresentador;

/**
 *
 * @author usuario
 */
public class VistaPrevia extends javax.swing.JFrame  implements IVistaPrevia{

    private VistaPreviaPresentador presentador;
    /**
     * Creates new form VistaPrevia1
     */
    public VistaPrevia() {
        initComponents();
    }
     public VistaPrevia(Integer dni) {
        initComponents();
        presentador = new VistaPreviaPresentador(this,dni);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vistaCarnet = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbFoto = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbNomAp = new javax.swing.JLabel();
        lbDni = new javax.swing.JLabel();
        lbDestino = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbEjemplar = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lbFechaVenc = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lbDireccion = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        vistaCarnet.setBackground(new java.awt.Color(255, 255, 255));
        vistaCarnet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("MUNICIPALIDAD DE BELLA VISTA - ÁREA DE LA JUVENTUD");

        jLabel3.setText("NOMBRE Y APELLIDO:");

        jLabel4.setText("DNI:");

        jLabel7.setText("DESTINO");

        lbNomAp.setText("NOMBRE Y APELLIDO:");

        lbDni.setText("DNI:");

        lbDestino.setText("DESTINO");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("EJEMPLAR");

        lbEjemplar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbEjemplar.setText("EJEMPLAR");

        jLabel15.setText("FECHA VENCIMIENTO ");

        lbFechaVenc.setText("FECHA VENCIMIENTO ");

        jLabel19.setText("DIRECCIÓN");

        lbDireccion.setText("DIRECCIÓN");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo100x100 - blanco.png"))); // NOI18N

        javax.swing.GroupLayout vistaCarnetLayout = new javax.swing.GroupLayout(vistaCarnet);
        vistaCarnet.setLayout(vistaCarnetLayout);
        vistaCarnetLayout.setHorizontalGroup(
            vistaCarnetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vistaCarnetLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(vistaCarnetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vistaCarnetLayout.createSequentialGroup()
                        .addGroup(vistaCarnetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(vistaCarnetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(vistaCarnetLayout.createSequentialGroup()
                                .addGroup(vistaCarnetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbFechaVenc, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbNomAp, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(265, 265, 265))
                    .addGroup(vistaCarnetLayout.createSequentialGroup()
                        .addGroup(vistaCarnetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(vistaCarnetLayout.createSequentialGroup()
                                .addGroup(vistaCarnetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(vistaCarnetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(vistaCarnetLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel1))
                                    .addGroup(vistaCarnetLayout.createSequentialGroup()
                                        .addGap(109, 109, 109)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbEjemplar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(vistaCarnetLayout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(101, 101, 101)
                                .addComponent(lbDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        vistaCarnetLayout.setVerticalGroup(
            vistaCarnetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vistaCarnetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(vistaCarnetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vistaCarnetLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGroup(vistaCarnetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(vistaCarnetLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(vistaCarnetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbEjemplar)
                                    .addComponent(jLabel13))
                                .addGap(84, 84, 84)
                                .addGroup(vistaCarnetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(vistaCarnetLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4))
                                    .addGroup(vistaCarnetLayout.createSequentialGroup()
                                        .addComponent(lbNomAp)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbDni)))
                                .addGap(18, 18, 18)
                                .addGroup(vistaCarnetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(lbDestino)))
                            .addGroup(vistaCarnetLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(vistaCarnetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(lbFechaVenc)))
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(vistaCarnetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(lbDireccion))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vistaCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(btnVolver))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(vistaCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVolver)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

   @Override
    public void setBeneficiario(Beneficiario b) {
        this.getLbDireccion().setText(b.getDireccion());
        this.getLbEjemplar().setText(String.valueOf(b.obtenerBeneficioActivo().getCarnet().getEjemplar()));
        this.getLbDni().setText(String.valueOf(b.getDni()));
        this.getLbFechaVenc().setText(b.obtenerBeneficioActivo().getFecVencimiento().toString());
        this.getLbFoto().setIcon(b.getFotografia());
        this.getLbNomAp().setText(b.getApellido()+", "+b.getNombre());
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lbDestino;
    private javax.swing.JLabel lbDireccion;
    private javax.swing.JLabel lbDni;
    private javax.swing.JLabel lbEjemplar;
    private javax.swing.JLabel lbFechaVenc;
    private javax.swing.JLabel lbFoto;
    private javax.swing.JLabel lbNomAp;
    private javax.swing.JPanel vistaCarnet;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnVolver() {
        return btnVolver;
    }

    public void setBtnVolver(JButton btnVolver) {
        this.btnVolver = btnVolver;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel13() {
        return jLabel13;
    }

    public void setjLabel13(JLabel jLabel13) {
        this.jLabel13 = jLabel13;
    }

    public JLabel getjLabel15() {
        return jLabel15;
    }

    public void setjLabel15(JLabel jLabel15) {
        this.jLabel15 = jLabel15;
    }

    public JLabel getjLabel19() {
        return jLabel19;
    }

    public void setjLabel19(JLabel jLabel19) {
        this.jLabel19 = jLabel19;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    public JLabel getLbDestino() {
        return lbDestino;
    }

    public void setLbDestino(JLabel lbDestino) {
        this.lbDestino = lbDestino;
    }

    public JLabel getLbDireccion() {
        return lbDireccion;
    }

    public void setLbDireccion(JLabel lbDireccion) {
        this.lbDireccion = lbDireccion;
    }

    public JLabel getLbDni() {
        return lbDni;
    }

    public void setLbDni(JLabel lbDni) {
        this.lbDni = lbDni;
    }

    public JLabel getLbEjemplar() {
        return lbEjemplar;
    }

    public void setLbEjemplar(JLabel lbEjemplar) {
        this.lbEjemplar = lbEjemplar;
    }

    public JLabel getLbFechaVenc() {
        return lbFechaVenc;
    }

    public void setLbFechaVenc(JLabel lbFechaVenc) {
        this.lbFechaVenc = lbFechaVenc;
    }

    public JLabel getLbFoto() {
        return lbFoto;
    }

    public void setLbFoto(JLabel lbFoto) {
        this.lbFoto = lbFoto;
    }

    public JLabel getLbNomAp() {
        return lbNomAp;
    }

    public void setLbNomAp(JLabel lbNomAp) {
        this.lbNomAp = lbNomAp;
    }

    public JPanel getVistaCarnet() {
        return vistaCarnet;
    }

    public void setVistaCarnet(JPanel vistaCarnet) {
        this.vistaCarnet = vistaCarnet;
    }


}
