/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package municipalidad.presentacion.vistas;

import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import municipalidad.dominio.Beneficiario;
import municipalidad.presentacion.presentadores.GenerarCarnetPresentador;
import municipalidad.presentacion.interfaces.IGenerarCarnet;
import municipalidad.presentacion.vistas.render.Render;

/**
 *
 * @author usuario
 */
public class VistaGenerarCarnet extends javax.swing.JFrame implements IGenerarCarnet {

    /**
     * Creates new form VistaGenerarCarnet
     */
    
    private final GenerarCarnetPresentador presentador;
    
    public VistaGenerarCarnet() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.presentador = new GenerarCarnetPresentador(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbCarnets = new javax.swing.JTable();
        rbSeleccionarTodo = new javax.swing.JRadioButton();
        btnConfirmar = new javax.swing.JButton();
        btnVistaPrevia = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbCarnets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbCarnets);

        rbSeleccionarTodo.setText("Seleccionar Todo");
        rbSeleccionarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSeleccionarTodoActionPerformed(evt);
            }
        });

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnVistaPrevia.setText("Vista Previa");
        btnVistaPrevia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVistaPreviaActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnVistaPrevia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnConfirmar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(rbSeleccionarTodo)
                                .addGap(147, 147, 147))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(162, 162, 162))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rbSeleccionarTodo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVistaPrevia)
                    .addComponent(btnConfirmar)
                    .addComponent(btnCancelar))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbSeleccionarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSeleccionarTodoActionPerformed
        if(this.getRbSeleccionarTodo().isSelected())
        {
            for(int i=0;i<this.getTbCarnets().getRowCount();i++)
            {
                this.getTbCarnets().setValueAt(true, i, 2);
            }
        }
        else
        {
             for(int i=0;i<this.getTbCarnets().getRowCount();i++)
            {
                this.getTbCarnets().setValueAt(false, i, 2);
            }
        }
        
        
    }//GEN-LAST:event_rbSeleccionarTodoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        confirmarImpresion();
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnVistaPreviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVistaPreviaActionPerformed
         if(this.getTbCarnets().getSelectedRows().length==1)
        {
             (new VistaPrevia((Integer) this.getTbCarnets().getValueAt(this.getTbCarnets().getSelectedRow(), 1))).setVisible(true);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Seleccione un Beneficiario", "Error", JOptionPane.ERROR_MESSAGE);

        }
        
       
    }//GEN-LAST:event_btnVistaPreviaActionPerformed

    
    @Override
    public void setBeneficiarios(ArrayList<Beneficiario> beneficiarios) {
        
         boolean[] editable = {false,false,true};
        this.getTbCarnets().setDefaultRenderer(Object.class, new Render());
        DefaultTableModel dt = new DefaultTableModel(new String[]{"BENEFICIARIO","DNI","IMPRIMIR"}, 0) {
 
            Class[] types = new Class[]{
                java.lang.Object.class,java.lang.Object.class,java.lang.Boolean.class
            };
 
            @Override
            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
            
            @Override
            public boolean isCellEditable(int row, int column){
                return editable[column];
            }
        };
        if(beneficiarios.size() > 0){
        for(int i=0; i< beneficiarios.size(); i++){
        Object fila[] = new Object[3];
        
        fila[0] = beneficiarios.get(i).getApellido();
        fila[1] = beneficiarios.get(i).getDni();
        fila[2] = false;
                

        dt.addRow(fila);
        
        }
        
        }
        
        this.getTbCarnets().setModel(dt);
    }
    
    
     private void confirmarImpresion() {
         
            int filasAImprimir = 0;
          for(int i=0;i<this.getTbCarnets().getRowCount();i++)
            {
                if((boolean)this.getTbCarnets().getValueAt(i, 2))
                {
                   filasAImprimir++;
                  this.presentador.seleccionarCarnet((Integer) this.getTbCarnets().getValueAt(i, 1));
                }
            }
         if(filasAImprimir>0)
         {
             this.presentador.confirmarImpresion();
         }
         else
         {
              JOptionPane.showMessageDialog(this, "Seleccione un Beneficiario", "Error", JOptionPane.ERROR_MESSAGE);
         }
           
    }

   
    
    
    
    
    
    public JButton getBtnConfirmar() {
        return btnConfirmar;
    }

    public void setBtnConfirmar(JButton btnConfirmar) {
        this.btnConfirmar = btnConfirmar;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JRadioButton getRbSeleccionarTodo() {
        return rbSeleccionarTodo;
    }

    public void setRbSeleccionarTodo(JRadioButton rbSeleccionarTodo) {
        this.rbSeleccionarTodo = rbSeleccionarTodo;
    }

    public JTable getTbCarnets() {
        return tbCarnets;
    }

    public void setTbCarnets(JTable tbCarnets) {
        this.tbCarnets = tbCarnets;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public void setBtnCancelar(JButton btnCancelar) {
        this.btnCancelar = btnCancelar;
    }

    public JButton getBtnVistaPrevia() {
        return btnVistaPrevia;
    }

    public void setBtnVistaPrevia(JButton btnVistaPrevia) {
        this.btnVistaPrevia = btnVistaPrevia;
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnVistaPrevia;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbSeleccionarTodo;
    private javax.swing.JTable tbCarnets;
    // End of variables declaration//GEN-END:variables

   
    
}
